version: "3"
services:
  
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  
  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - postgres:postgres  # my database container is called postgres, not db
    environment:
      DATABASE_URL: postgres://prisma:prisma@postgres:5432/prisma?sslmode=disable
    depends_on:
      - postgres

  graphql-server:
    build:
      context: ./graphql-server
    volumes:
      - ./graphql-server:/go/src/app
    working_dir: /go/src/app
    ports:
      - 5000:8080
    depends_on:
      - postgres
      - prisma
    links:
      - prisma:prisma
    restart: always
    
    
volumes:
  postgres: ~