// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type UpdateStaffAttendInput struct {
	IsAttend     *bool `json:"isAttend"`
	InTimeIndex  *int  `json:"inTimeIndex"`
	OutTimeIndex *int  `json:"outTimeIndex"`
}
