// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type Admin struct {
	ID        string  `json:"id"`
	Name      *string `json:"name"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Auth struct {
	User  string `json:"user"`
	Token string `json:"token"`
}

type UpdateStaffAttendInput struct {
	IsAttend     *bool `json:"isAttend"`
	InTimeIndex  *int  `json:"inTimeIndex"`
	OutTimeIndex *int  `json:"outTimeIndex"`
}
